### ISSUE TITLE
关于函数多次使用的问题

### ISSUE THREAD

**Issue by Farewell1024** [FreeGIS/postgis_LayerTransform#2]
对同一列多次使用转换函数，是否会造成坐标的多次偏移？

**Comment by FreeGIS** [comment]
旧版的会。请使用新版，已完全重写。

**Comment by Farewell1024** [comment]
多谢大神。
现在意味着我第一次转换一批数据后，再次插入一部分，并进行转换，第一批数据也不会再次偏移，对吗

**Comment by Farewell1024** [comment]
还有一个问题，大神
之前的函数在原字段修改，现在为啥要新添加一个字段..

**Comment by FreeGIS** [comment]
原先只有一个geom，转换后就更改了原来数据。现在的geom是原来的数据，无论如何不会改，偏移的结果存到了transform_geom中存储了。
