### ISSUE TITLE
gcj2wgs时错误

### ISSUE THREAD

**Issue by guyanf** [FreeGIS/postgis_LayerTransform#3]
国测局坐标往wgs84转换时报错，提示缺少gcj2wgs函数，看了sql，应该是没有写完整。

**Comment by guyanf** [comment]
SELECT freegis_coordinate_transform('public', 'temp_aa', 'GCJ2WGS');
注意:  正在将图形拆分成点...
注意:  图形拆分成点完成！
注意:  对拆分成点后的数据集建索引...
注意:  对拆分成点后的数据集建索引完成！
注意:  对拆分点进行偏移计算...
错误:  函数 wgs2gcj(geometry) 不存在
LINE 1: SELECT WGS2GCJ(gcj_point)
               ^
HINT:  没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换.
QUERY:  SELECT WGS2GCJ(gcj_point)
CONTEXT:  在赋值的第10行的PL/pgSQL函数freegis_gcj2wgs(geometry)
SQL 语句 "update _split_result set target_geom=FreeGIS_GCJ2WGS(source_geom)"
在EXECUTE的第97行的PL/pgSQL函数_freegis_coordinate_transform_2(text,text,freegis_coordinate_transform_type)
在RETURN的第11行的PL/pgSQL函数freegis_coordinate_transform(text,text,freegis_coordinate_transform_type)


存储的数据为linestring。

**Comment by guyanf** [comment]
line116；
old：
	_gcj_point:=WGS2GCJ(gcj_point);

change to：
	_gcj_point:=FreeGIS_WGS2GCJ(gcj_point);

**Comment by FreeGIS** [comment]
好的，感谢提醒，已经修正。应该是测试没覆盖。。。
